apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: strr-renewal-reminder-pipeline
description: Deployment pipeline
serialPipeline:
 stages:
 - targetId: bcrbk9-dev
   profiles: [dev]
   strategy:
    standard:
      verify: false
   deployParameters:
   - values:
      deploy-env: "development"
      deploy-project-id: "bcrbk9-dev"
      job-name: "strr-renewal-reminder-dev"
      cloudsql-instances: "bcrbk9-dev:northamerica-northeast1:strr-db-dev"
      run-command: "./run.sh"
      service-account: "sa-job@bcrbk9-dev.iam.gserviceaccount.com"
 - targetId: bcrbk9-test
   profiles: [test]
   strategy:
    standard:
      verify: false
   deployParameters:
   - values:
      deploy-env: "test"
      deploy-project-id: "bcrbk9-test"
      job-name: "strr-renewal-reminder-test"
      cloudsql-instances: "bcrbk9-test:northamerica-northeast1:strr-db-test"
      run-command: "./run.sh"
      service-account: "sa-job@bcrbk9-test.iam.gserviceaccount.com"
 - targetId: bcrbk9-uat
   profiles: [uat]
   strategy:
    standard:
      verify: false
   deployParameters:
   - values:
      deploy-env: "uat"
      deploy-project-id: "bcrbk9-test"
      job-name: "strr-renewal-reminder-uat"
      cloudsql-instances: "bcrbk9-test:northamerica-northeast1:strr-db-test"
      run-command: "./run.sh"
      service-account: "sa-job@bcrbk9-test.iam.gserviceaccount.com"
 - targetId: bcrbk9-sandbox
   profiles: [sandbox]
   strategy:
    standard:
      verify: false
   deployParameters:
   - values:
      deploy-env: "sandbox"
      deploy-project-id: "bcrbk9-tools"
      job-name: "strr-renewal-reminder-sandbox"
      cloudsql-instances: "bcrbk9-tools:northamerica-northeast1:strr-db-sandbox"
      run-command: "./run.sh"
      service-account: "sa-job@bcrbk9-tools.iam.gserviceaccount.com"
 - targetId: bcrbk9-prod
   profiles: [prod]
   strategy:
    standard:
      verify: false
   deployParameters:
   - values:
      deploy-env: "production"
      deploy-project-id: "bcrbk9-prod"
      job-name: "strr-renewal-reminder-prod"
      cloudsql-instances: "bcrbk9-prod:northamerica-northeast1:strr-db-prod"
      run-command: "./run.sh"
      service-account: "sa-job@bcrbk9-prod.iam.gserviceaccount.com"
