name: STRR NOC EXPIRY JOB CI

on:
  pull_request:
    paths:
      - "jobs/noc_expiry/**"
      - "src/strr_api/models/**"
      - "src/strr_api/services/**"
      - "src/strr_api/enums/**"
      - "src/strr_api/exceptions/**"
      - "src/strr_api/utils/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./jobs/noc_expiry

jobs:
  strr-auto-approval-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/backend-ci.yaml@main
    with:
      app_name: "strr-noc-expiry"
      working_directory: "./jobs/noc_expiry"
      codecov_flag: "nocjob"
